[package]
name = "attractors-rs"
version = "0.1.0"
authors = ["Chris Whitworth <chris.whitworth@microsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
rand = "0.8.3"